### ISSUE TITLE
Update the add-on reports automatically

### ISSUE THREAD

**Issue by tdulcet** [thundernest/thundernest.github.io#1]
@jobisoft - Consider setting up GitHub Actions to update these add-on reports automatically. TB add-on developers would then get more frequent updates and you would have more time to add new MailExtension APIs... 😉

It looks like GitHub Actions is [already being used](https://github.com/thundernest/thundernest.github.io/actions) to build and deploy the pages, so you would just need to additionally use it to generate and commit the updated reports. GitHub Actions supports automatically running [on a schedule](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule), so it should be trivial to setup. I believe the underlining ATN data is only updated weekly, but you could config it to update the reports daily or even more frequently if necessary. Hope that helps.

BTW, as a TB add-on developer myself, these add-on reports are very interesting and useful. Thanks for maintaining them!

**Comment by jobisoft** [comment]
I do not think I can run the database extraction script (get_addon_data.js) on Github CI. It takes up to 10 minutes to complete locally.

**Comment by tdulcet** [comment]
This should not be an issue. I have much [more complex scripts](https://github.com/tdulcet/Distributed-Computing-Scripts/actions) on GitHub Actions that take close to an hour to complete...

**Comment by jobisoft** [comment]
Feel brave to set this up for us? What access rights do you need for that?

**Comment by tdulcet** [comment]
I just looked up the [official usage limits](https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits). GitHub Actions jobs are limited to 6 hours and accounts/organizations are limited to 20 concurrent jobs, so a 10 minute job here should not be an issue. 🙂

Sure, I can look into creating a PR... I do not believe I would need any special access rights, although you would of course need to approve the workflow to run and would also need to [change a setting](https://docs.github.com/en/actions/security-guides/automatic-token-authentication) to allow it to commit back to the repository.

Do you know what day and time (in the UTC/GMT time zone) the data on ATN is updated? I could schedule this run right after that or at another day/time that you would prefer instead.

**Comment by jobisoft** [comment]
There is no central-scheduled update of the DB. When an add-on submission has been (auto-) approved, it is live instantly. But we do have an external cache - I think it is cloudflare, but I am no expert there - and that does need some time to update the data it serves. But I do not know when that happens. I guess you can pick any time of the day to run the script.

**Comment by tdulcet** [comment]
OK, thanks for the information. I have noticed that the stated number of users on each add-on listing on ATN update weekly on Sundays (in my timezone) and this number is same as what is listed on these reports, so I was not sure if the other data was also updated at that same time...

Anyway, in my PR (#3) I set the reports to update at noon (12:00) UTC, but I am of course happy to change this if you would prefer a different time. I also set them to update daily, mainly so we could get faster feedback to verify that this works as expected, but I am happy to change that as well if you would prefer less frequent updates.

**Comment by jobisoft** [comment]
As stated in the PR, I do not want to risk generating false reports, which are only based on updated ATN data, without also updating the metadata from the script itself.

**Comment by tdulcet** [comment]
Please consider reopening this issue so that we can find a solution.

As I mentioned in the PR, we could instead push the changes to a separate branch, which would allow you to review them and make any needed manual fixes before merging them with the main branch, which would then update the website. This would still presumably save you time and allow for more frequent updates of the reports.

Another option would be to add a note to the top of reports with the date of when the metadata was least updated, so that the AMO data could be automatically updated, but users would still be informed that the metadata may be outdated.

**Comment by jobisoft** [comment]
See my comments in https://github.com/thunderbird/thunderbird.github.io/pull/3#issuecomment-2848639285

Github action for automatic updates has been implemented at the new repo for the reports.
