### ISSUE TITLE
Use SVG badges in the add-on reports

### ISSUE THREAD

**Issue by tdulcet** [thundernest/thundernest.github.io#2]
I have noticed for a while that the badges all look fuzzy on my 4K monitor (click on the below screenshot for example):
![image](https://user-images.githubusercontent.com/15305150/234663744-036de773-22a7-4fc5-a8ea-26e7bcff1d59.png)

The [Shields.io](https://shields.io/) service you are using already supports SVG badges, so the solution would be to use those instead of the older PNG badges that are being used now. Specifically, change the `.png` near the end of this line to `.svg`:
https://github.com/thundernest/thundernest.github.io/blob/e2e9be9b0850a89107f9aa08ee8eb79ddd95fa28/add-on-reports-generator/build_reports.js#L1170

**Comment by jobisoft** [comment]
Done. I tried to credit this to you. In order to get your contributions flagged correctly, feel free to create pull requests in the future.

Thanks for your help!
